<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="DocTestRunner.fs" />
    <Compile Include="Library.fs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FsLiveDocs.Core\FsLiveDocs.Core.fsproj" />
  </ItemGroup>

</Project>
